sudo: required
services:
    - docker
before_install:
    - docker build -t 683202/react-test -f ./client/Dockerfile.dev ./client
scripts:
    # Run the test after running the container. --coverage makes sure that the test doesn't enter watch mode and returns with a status code.
    - docker run -e CI=true 683202/react-test npm test -- --coverage
after_success:
    # create the production version of the apps.
    - docker build -t 683202/multi-client ./client
    - docker build -t 683202/multi-nginx ./nginx
    - docker build -t 683202/multi-api ./server
    - docker build -t 683202/multi-worker ./worker
    # login to docker hub.
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Now push all the app images to the docker hub.
    - docker push 683202/multi-client
    - docker push 683202/multi-nginx
    - docker push 683202/multi-api
    - docker push 683202/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "multi-docker-v2"
    env: "MultiDockerV2-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-526847251372"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY