version: '3'

services: 
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: './nginx'
        ports: 
            - "3050:80"
        depends_on: 
            - api
            - client
    postgres:
        image: "postgres:latest"
        environment: 
            - POSTGRES_PASSWORD=postgres_password
        ports: 
            - "5432:5432"
    redis:
        image: "redis:latest"
        ports: 
            - "6379:6379"
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: "./client"
        volumes: 
            - /app/node_modules
            - ./client:/app
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: "./server"
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_HOST=postgres
            - PG_USER=postgres
            - PG_PORT=5432
            - PG_DATABASE=postgres
            - PG_PASSWORD=postgres_password
        depends_on: 
            - redis
            - postgres
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: "./worker"
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on: 
            - redis